######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 2 10:46:50 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += globj.h mainwindow.h
SOURCES += globj.cpp main.cpp mainwindow.cpp
QT += opengl
